"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";

/**
 * Seller profile settings — persisted to localStorage so the form
 * values survive page refreshes.
 *
 * The store is keyed by `sellerId` so each seller has their own profile.
 */

export interface SellerProfile {
  sellerId: string;
  storeName: string;
  description: string;
  email: string;
  address: string;
  // Discount code (display-only, generated by the seller)
  discountCode: string;
}

interface SellerProfileState {
  profiles: Record<string, SellerProfile>;
  getProfile: (sellerId: string) => SellerProfile | undefined;
  saveProfile: (profile: SellerProfile) => void;
  generateDiscountCode: (sellerId: string) => string;
}

function randomCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  let code = "KOCH-";
  for (let i = 0; i < 4; i++) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}

export const useSellerProfile = create<SellerProfileState>()(
  persist(
    (set, get) => ({
      profiles: {},
      getProfile: (sellerId) => get().profiles[sellerId],
      saveProfile: (profile) =>
        set((s) => ({
          profiles: { ...s.profiles, [profile.sellerId]: profile },
        })),
      generateDiscountCode: (sellerId) => {
        const code = randomCode();
        const existing = get().profiles[sellerId];
        if (existing) {
          set((s) => ({
            profiles: {
              ...s.profiles,
              [sellerId]: { ...existing, discountCode: code },
            },
          }));
        }
        return code;
      },
    }),
    { name: "kochneshin-seller-profile" }
  ),
);
